geekshop/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp.views import home, products, contact, context
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path('', home, name='home'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', contact, name='contact'),
    path('context/', context),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('control/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatar', blank=True)
    age = models.PositiveIntegerField(verbose_name='Возраст')

geekshop/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):

    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):

    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Вы слишком молоды!')
        return data


class ShopUserEditForm(UserChangeForm):

    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'age',  'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Слишком молод!')
        return data

geekshop/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse
from authapp.forms import ShopUserLoginForm
from authapp.forms import ShopUserRegisterForm
from authapp.forms import ShopUserEditForm

# Create your views here.


def login(request):
    title = 'вход'

    next_param = request.GET.get('next', '')

    login_form = ShopUserLoginForm(data=request.POST or None)

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            return HttpResponseRedirect(reverse('home'))

    context = {
        'title': title,
        'login_form': login_form,
        'next_param': next_param,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('home'))


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()
    context = {
        'title': title,
        'register_form': register_form,
    }
    return render(request, 'authapp/register.html', context)


def edit(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)

    context = {
        'title': title,
        'edit_form': edit_form
    }
    return render(request, 'authapp/edit.html', context)

geekshop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
    <div class="container">
        <div class="login">
            <div class="h2 text-center head">
                {{ title| title }}
            </div>

            {% block content %}

            {% endblock %}
        </div>
    </div>
</body>
</html>

geekshop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        <input class="form-control" type="submit"  value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'home' %}" class="">на главную</a>
    </button>
<div class="user_avatar"><img src="/media/{{ user.avatar }}"></div>
{% endblock %}

geekshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {% if next_param %}
            <input type="hidden" name="next" value="{{ next_param }}">
        {% endif %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>
{% endblock %}

geekshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>
{% endblock %}