geekshop/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path
from basketapp import views as basketapp

app_name = 'basketapp'


urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp.views import home, products, contact, context
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path('', home, name='home'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', contact, name='contact'),
    path('context/', context),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('control/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop/mainapp/models.py
from django.db import models


# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, ProductCategory
from basketapp.models import Basket
import random


main_menu_links = [
    {'href': 'home', 'name': 'домой'},
    {'href': 'products:index', 'name': 'продукты'},
    {'href': 'contact', 'name': 'контакты'},
]


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    return []


def get_hot_product():
    return random.sample(list(Product.objects.all()), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products


def home(request):
    basket = get_basket(request.user)
    title = 'магазин'
    products = Product.objects.all()[:3]
    context = {
        'title': title,
        'main_menu_links': main_menu_links,
        'products': products,
        'basket': basket,
    }
    return render(request, 'mainapp/index.html', context)


def products(request, pk=None):
    basket = get_basket(request.user)
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    product_menu_links = ProductCategory.objects.all()
    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all().order_by('price')
            categoty_item = {'name': 'все'}
        else:
            categoty_item = get_object_or_404(ProductCategory, pk=pk)
            products_list = Product.objects.filter(category__pk=pk).order_by('price')
        context = {
            'title': 'продукты',
            'main_menu_links': main_menu_links,
            'product_menu_links': product_menu_links,
            'products': products_list,
            'category': categoty_item,
            'basket': basket,
            'hot_product': hot_product,
        }
        return render(request, 'mainapp/products_list.html', context)

    context = {
        'title': 'продукты',
        'main_menu_links': main_menu_links,
        'product_menu_links': product_menu_links,
        'same_products': same_products,
        'basket': basket,
        'hot_product': hot_product,
    }
    return render(request, 'mainapp/products.html', context)


def contact(request):
    basket = get_basket(request.user)
    context = {
        'title': 'контакты',
        'main_menu_links': main_menu_links,
        'basket': basket,
    }
    return render(request, 'mainapp/contact.html', context)


def context(request):
    context = {
        'title': 'Test context',
        'header': 'Добро пожаловать на сайт',
        'username': 'John',
        'products': [
            {'name': 'Стулья', 'price':  6789},
            {'name': 'Диваны', 'price':  12345},
            {'name': 'Столы', 'price':  5555},
        ]
    }
    return render(request, 'mainapp/test_context.html', context)


def product(request, pk):
    product_menu_links = ProductCategory.objects.all()
    context = {
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
        'product_menu_links': product_menu_links,
    }
    return render(request, 'mainapp/product.html', context)

geekshop/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

    <title>
    {% block title %}
        Дефолтное название
    {% endblock %}
    </title>

    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}

</head>
<body>
	<div class="container">
		{% block menu %}
        {% endblock %}

        {% block content %}
        {% endblock %}
	</div>

    {% block footer %}
        <div class="footer">
            <div class="clearfix">
                <div class="text-footer">
                    <h3>контакты</h3>
                </div>
                <div class="text-footer">
                    <h3>полезная информация</h3>
                </div>
                <div class="text-footer clearfix">
                    <h3>Оставайтесь на связи</h3>
                    <p>Подписаться на новости и рассылки</p>
                    <form>
                        <input type="email" name="email" placeholder="ваш email">
                        <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                    </form>
                </div>
            </div>
            <p class="small">&copy; GB {% now "Y" %}</p>
            <div class="social">
                <a href="#" class="social1"></a>
                <a href="#" class="social2"></a>
                <a href="#" class="social3"></a>
                <a href="#" class="social4"></a>
            </div>
            <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
        </div>
    {% endblock %}
</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

	{% block title %}
		{{ title| title }}
	{% endblock %}

</head>
<body>
	<div class="container">

		{% block menu %}
		<div class="hero">
			<div class="header clearfix">
				{% include 'mainapp/includes/inc_main_menu.html' %}
			</div>
			<h1>наши контакты</h1>
		</div>
		{% endblock %}

		{% block content %}
		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
		{% endblock %}

	</div>	

</body>
</html>

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

	{% block title %}
		{{ title|title }}
	{% endblock %}

</head>
<body>
	<div class="container">
		{% block menu %}
		<div class="slider">
			<div class="header clearfix">
				{% include 'mainapp/includes/inc_main_menu.html' %}
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>
		{% endblock %}

		{% block content %}
		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
				<div class="tab-content">
					{% for product in products %}
						<div class="block">
							<a href="{% url 'mainapp:product' product.pk %}">
								<img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
								<div class="text">
									<h3>Категория продукта: {{ product.category.name }}</h3>
									<h4>Название продукта: {{ product.name }}</h4>
									<p>Описание продукта: {{ product.description }}</p>
									<p>Цена: {{ product.price }}</p>
								</div>
							</a>
						</div>
					{% endfor %}
				</div>
		</div>

		<div class="clr"></div>

		{% endblock %}
	</div>

</body>
</html>

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

	{% block title %}
		{{ title|title }}
	{% endblock %}

</head>
<body>
	<div class="container">
		{% block menu %}
		<div class="hero-white">
			<div class="header clearfix">
				{% include 'mainapp/includes/inc_main_menu.html' %}
			</div>
		</div>
		{% endblock %}

		{% block content %}
		<div class="details">
			<div class="links clearfix">
				{% include 'mainapp/includes/inc_categories_menu.html' %}
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="/media/{{ product.image }}">
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">{{ product.name }}</h3><br>
					<p class="price">{{ product.price|floatformat:2 }}<span>руб</span></p>
					<a href="{% url 'basket:add' product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>{{ product.description }}</p>
					</div>
				</div>
			</div>


		</div>

		<div class="clr"></div>
		{% endblock %}
	</div>
</body>
</html>

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

	{% block title %}
		{{ title|title }}
	{% endblock %}
</head>
<body>
	<div class="container">
		{% block menu %}
		<div class="hero-white">
			<div class="header clearfix">
				{% include 'mainapp/includes/inc_main_menu.html' %}
			</div>
		</div>
		{% endblock %}

		{% block content %}
		<div class="details">
			<div class="links clearfix">
				{% include 'mainapp/includes/inc_categories_menu.html' %}
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="/media/{{ hot_product.image }}">
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">{{ hot_product.name }}</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price">{{ hot_product.price|floatformat:2 }}<span>руб</span></p>
					<a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>{{ hot_product.description }}</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					{% for product in same_products %}
						<div class="block">
							<a href="{% url 'mainapp:product' product.pk %}"><img src="/media/{{ product.image }}" alt="">
								<div class="text">
									<img src="{% static 'img/icon-hover.png' %}" alt="img">
									<h4>{{ product.name }}</h4>
									<p>{{ product.category.name }}</p>
								</div>
							</a>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>

		<div class="clr"></div>
		{% endblock %}
	</div>
</body>
</html>

geekshop/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

	{% block title %}
		{{ title|title }}
	{% endblock %}
</head>
  <body>
	<div class="container">
      {% block menu %}
        <div class="hero-white">
          <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
          </div>
        </div>
      {% endblock %}

      {% block content %}
        <div class="details">
          <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
          </div>

          <div class="products_list">
            <div class="title clearfix">
              <h2>
                Категория: "{{ category.name|title }}"
              </h2>
            </div>
            <div class="category-products clearfix">

              {% for product in products %}
                <div class="block">
                  <a href="{% url 'mainapp:product' product.pk %}">
                    <img src="/media/{{ product.image }}" alt="product">
                    <div class="text">
                      <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.description }}</p>
                    </div>
                  </a>
                </div>
              {% endfor %}

            </div>
          </div>
        </div>

        <div class="clr"></div>
      {% endblock %}
    </div>
  </body>
</html>

geekshop/mainapp/templates/mainapp/test_context.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
</head>
<body>
    <h1>{{header}}</h1>
    <p>{{username}}</p>
    {% for product in products %}
        <h3>{{ product.name }}</h3>
        <p>{{ product.price }}</p>
    {% endfor %}
</body>
</html>